<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260717162104 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE availability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, trip_project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3FB7A2BFA76ED395 ON availability (user_id)');
        $this->addSql('CREATE INDEX IDX_3FB7A2BFE37FC48A ON availability (trip_project_id)');
        $this->addSql('CREATE TABLE destination_proposal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, city VARCHAR(120) NOT NULL, country VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, estimated_cost NUMERIC(10, 2) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, proposed_by_id INT NOT NULL, trip_project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E1555443DAB5A938 ON destination_proposal (proposed_by_id)');
        $this->addSql('CREATE INDEX IDX_E1555443E37FC48A ON destination_proposal (trip_project_id)');
        $this->addSql('CREATE TABLE expense (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, amount NUMERIC(10, 2) NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, paid_by_id INT NOT NULL, trip_project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2D3A8DA67F9BC654 ON expense (paid_by_id)');
        $this->addSql('CREATE INDEX IDX_2D3A8DA6E37FC48A ON expense (trip_project_id)');
        $this->addSql('CREATE TABLE expense_share (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, expense_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C0E3A60A76ED395 ON expense_share (user_id)');
        $this->addSql('CREATE INDEX IDX_4C0E3A60F395DB7B ON expense_share (expense_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_expense_share ON expense_share (user_id, expense_id)');
        $this->addSql('CREATE TABLE trip_participant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(30) NOT NULL, status VARCHAR(30) NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, trip_project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_23BECC9BA76ED395 ON trip_participant (user_id)');
        $this->addSql('CREATE INDEX IDX_23BECC9BE37FC48A ON trip_participant (trip_project_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_trip ON trip_participant (user_id, trip_project_id)');
        $this->addSql('CREATE TABLE vote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, destination_proposal_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5A108564A76ED395 ON vote (user_id)');
        $this->addSql('CREATE INDEX IDX_5A108564D14BCB63 ON vote (destination_proposal_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_destination_vote ON vote (user_id, destination_proposal_id)');
        $this->addSql('ALTER TABLE availability ADD CONSTRAINT FK_3FB7A2BFA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE availability ADD CONSTRAINT FK_3FB7A2BFE37FC48A FOREIGN KEY (trip_project_id) REFERENCES trip_project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE destination_proposal ADD CONSTRAINT FK_E1555443DAB5A938 FOREIGN KEY (proposed_by_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE destination_proposal ADD CONSTRAINT FK_E1555443E37FC48A FOREIGN KEY (trip_project_id) REFERENCES trip_project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA67F9BC654 FOREIGN KEY (paid_by_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA6E37FC48A FOREIGN KEY (trip_project_id) REFERENCES trip_project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense_share ADD CONSTRAINT FK_4C0E3A60A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense_share ADD CONSTRAINT FK_4C0E3A60F395DB7B FOREIGN KEY (expense_id) REFERENCES expense (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip_participant ADD CONSTRAINT FK_23BECC9BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip_participant ADD CONSTRAINT FK_23BECC9BE37FC48A FOREIGN KEY (trip_project_id) REFERENCES trip_project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vote ADD CONSTRAINT FK_5A108564A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vote ADD CONSTRAINT FK_5A108564D14BCB63 FOREIGN KEY (destination_proposal_id) REFERENCES destination_proposal (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE availability DROP CONSTRAINT FK_3FB7A2BFA76ED395');
        $this->addSql('ALTER TABLE availability DROP CONSTRAINT FK_3FB7A2BFE37FC48A');
        $this->addSql('ALTER TABLE destination_proposal DROP CONSTRAINT FK_E1555443DAB5A938');
        $this->addSql('ALTER TABLE destination_proposal DROP CONSTRAINT FK_E1555443E37FC48A');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA67F9BC654');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA6E37FC48A');
        $this->addSql('ALTER TABLE expense_share DROP CONSTRAINT FK_4C0E3A60A76ED395');
        $this->addSql('ALTER TABLE expense_share DROP CONSTRAINT FK_4C0E3A60F395DB7B');
        $this->addSql('ALTER TABLE trip_participant DROP CONSTRAINT FK_23BECC9BA76ED395');
        $this->addSql('ALTER TABLE trip_participant DROP CONSTRAINT FK_23BECC9BE37FC48A');
        $this->addSql('ALTER TABLE vote DROP CONSTRAINT FK_5A108564A76ED395');
        $this->addSql('ALTER TABLE vote DROP CONSTRAINT FK_5A108564D14BCB63');
        $this->addSql('DROP TABLE availability');
        $this->addSql('DROP TABLE destination_proposal');
        $this->addSql('DROP TABLE expense');
        $this->addSql('DROP TABLE expense_share');
        $this->addSql('DROP TABLE trip_participant');
        $this->addSql('DROP TABLE vote');
    }
}
