<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260820202950 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE destination_vote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, trip_project_id INT NOT NULL, destination_proposal_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F9B10C55A76ED395 ON destination_vote (user_id)');
        $this->addSql('CREATE INDEX IDX_F9B10C55E37FC48A ON destination_vote (trip_project_id)');
        $this->addSql('CREATE INDEX IDX_F9B10C55D14BCB63 ON destination_vote (destination_proposal_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_trip_destination_vote ON destination_vote (user_id, trip_project_id)');
        $this->addSql('ALTER TABLE destination_vote ADD CONSTRAINT FK_F9B10C55A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE destination_vote ADD CONSTRAINT FK_F9B10C55E37FC48A FOREIGN KEY (trip_project_id) REFERENCES trip_project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE destination_vote ADD CONSTRAINT FK_F9B10C55D14BCB63 FOREIGN KEY (destination_proposal_id) REFERENCES destination_proposal (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE destination_vote DROP CONSTRAINT FK_F9B10C55A76ED395');
        $this->addSql('ALTER TABLE destination_vote DROP CONSTRAINT FK_F9B10C55E37FC48A');
        $this->addSql('ALTER TABLE destination_vote DROP CONSTRAINT FK_F9B10C55D14BCB63');
        $this->addSql('DROP TABLE destination_vote');
    }
}
